# Central npxG data policy

USE_NPXG_FEATURE = False
NPXG_FIELD = "shooting.np_expected_goals"

NPXG_MIN_PLAYER_COVERAGE = 0.90
NPXG_MAX_SEASON_COVERAGE_DROP = 0.20
NPXG_MIN_VALID_APPEARANCES = 3
NPXG_MIN_VALID_MINUTES = 180.0